import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen justify-center items-center bg-gradient-to-br from-purple-800 to-purple-700`}>
        <main className="h-5/6 w-11/12 bg-white rounded-md">
          {children}
        </main>
      </body>
    </html>
  )
}
